namespace FoodEcommerceWebAPI.Models.Entities
{
    /// <summary>
    /// AddressEntity represents a physical address associated with a user.
    /// 
    /// Users can have multiple addresses for different purposes such as delivery, billing,
    /// or alternate locations. Each address is linked to a specific user and can be marked
    /// as the default address for quick selection during checkout.
    /// 
    /// Example: A user might have a home address and a work address, with the home address set as default.
    /// </summary>
    public class AddressEntitiy
    {
        /// <summary>
        /// Primary Key (PK)
        /// Unique identifier for each address record in the database.
        /// Auto-generated by the database.
        /// </summary>
        public int ID { get; set; }

        /// <summary>
        /// Foreign Key (FK) - References UserEntity
        /// Identifies which user this address belongs to.
        /// A required field that links this address to a specific customer.
        /// </summary>
        public required int Userid { get; set; }

        /// <summary>
        /// The street address line.
        /// Contains the street name, building number, apartment/suite number, etc.
        /// A required field that must be provided when creating an address.
        /// 
        /// Example: "123 Main Street, Apt 4B" or "456 Oak Avenue, Suite 100"
        /// </summary>
        public required string streetAddress { get; set; }

        /// <summary>
        /// The city or town name.
        /// Represents the municipal area where the address is located.
        /// A required field that must be provided when creating an address.
        /// 
        /// Example: "New York", "Los Angeles", "Chicago"
        /// </summary>
        public required string city { get; set; }

        /// <summary>
        /// The state or province abbreviation.
        /// Represents the state or province of the address.
        /// A required field that must be provided when creating an address.
        /// 
        /// Example: "NY" for New York, "CA" for California, "TX" for Texas
        /// </summary>
        public required string state { get; set; }

        /// <summary>
        /// The postal/zip code.
        /// Represents the ZIP or postal code for the address.
        /// A required field that must be provided when creating an address.
        /// Used for mail delivery and geographical sorting.
        /// 
        /// Example: "10001" for New York, "90001" for Los Angeles
        /// </summary>
        public required string zipCode { get; set; }

        /// <summary>
        /// Flag indicating if this is the user's default address.
        /// When set to true, this address is suggested as the default during checkout.
        /// A user can have multiple addresses but typically only one default address.
        /// A required field that must be explicitly set (true or false) when creating an address.
        /// 
        /// Example: true for home address (default), false for work address (alternate)
        /// </summary>
        public required bool IsDefault { get; set; }
    }
}
