namespace FoodEcommerceWebAPI.Models.Entities
{
    /// <summary>
    /// CartItemEntity represents an individual item in a shopping cart.
    /// 
    /// This entity acts as a junction table between Cart and FoodItems, allowing users to add
    /// multiple food items to their cart with specified quantities before checkout.
    /// 
    /// Example: A user's cart might contain 2 Pizzas and 3 Burgers, represented as two separate CartItem records.
    /// </summary>
    public class CartItemEntity
    {
        /// <summary>
        /// Primary Key (PK)
        /// Unique identifier for each cart item record in the database.
        /// Auto-generated by the database.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Foreign Key (FK) - References CartEntity
        /// Identifies which cart this item belongs to.
        /// Links this cart item to a specific user's shopping cart.
        /// </summary>
        public int CartId { get; set; }

        /// <summary>
        /// Foreign Key (FK) - References FoodItemsEntity
        /// Identifies which food product this cart item represents.
        /// Links this cart item to the product details (name, price, etc.).
        /// </summary>
        public int FoodItemId { get; set; }

        /// <summary>
        /// The quantity of the food item in the cart.
        /// Represents how many units of the food product the user wants to purchase.
        /// Must be a positive integer (e.g., 1, 2, 5).
        /// </summary>
        public int Quantity { get; set; }

        /// <summary>
        /// Navigation property to the parent Cart entity.
        /// Provides access to the cart that contains this item without needing manual joins.
        /// Uses the CartId foreign key to establish the relationship.
        /// 
        /// Example: cartItem.Cart will return the CartEntity object containing this item.
        /// </summary>
        public virtual CartEntity Cart { get; set; } = null!;

        /// <summary>
        /// Navigation property to the FoodItemsEntity (Product).
        /// Provides access to the product details (name, description, price, etc.) without needing manual joins.
        /// Uses the FoodItemId foreign key to establish the relationship.
        /// 
        /// Example: cartItem.FoodItem will return the FoodItemsEntity object with product information.
        /// </summary>
        public virtual FoodItemsEntity FoodItem { get; set; } = null!;
    }
}
