namespace FoodEcommerceWebAPI.Models.Entities
{
    /// <summary>
    /// CartEntity represents a shopping cart for a user.
    /// 
    /// Each user has a cart where they can add food items before checkout.
    /// The cart contains multiple cart items, each representing a food product with its quantity.
    /// The cart is temporary and is typically converted into an order upon checkout.
    /// 
    /// Example: A user's cart might contain 2 Pizzas and 3 Burgers waiting to be purchased.
    /// </summary>
    public class CartEntity
    {
        /// <summary>
        /// Primary Key (PK)
        /// Unique identifier for each shopping cart in the database.
        /// Auto-generated by the database.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Foreign Key (FK) - References UserEntity
        /// Identifies which user this cart belongs to.
        /// Links this shopping cart to a specific customer account.
        /// A required field that must be provided when creating a cart.
        /// Each user typically has one active cart.
        /// </summary>
        public required int UserID { get; set; }

        /// <summary>
        /// The date and time when the cart was last updated.
        /// Records when items were added, removed, or quantity was changed.
        /// A required field that tracks cart activity.
        /// Used to identify abandoned carts and clean up old/expired carts.
        /// 
        /// Example: 2026-01-20 14:30:45 represents when the user last modified their cart
        /// </summary>
        public required DateTime lastUpdated { get; set; }

        /// <summary>
        /// Navigation property to the collection of CartItems.
        /// Represents all items that are currently in this shopping cart.
        /// A one-to-many relationship where one cart can have multiple items.
        /// Initialized as an empty list to prevent null reference exceptions.
        /// 
        /// Example: cart.CartItems returns a list of all items in the user's cart.
        /// </summary>
        public virtual ICollection<CartItemEntity> CartItems { get; set; } = new List<CartItemEntity>();

        /// <summary>
        /// Navigation property to the User entity.
        /// Provides access to the user who owns this cart.
        /// Optional property (nullable) - allows access to user details without needing separate queries.
        /// 
        /// Example: cart.User will return the UserEntity object containing the cart owner's information.
        /// </summary>
        public virtual UserEntity? User { get; set; }
    }
}