namespace FoodEcommerceWebAPI.Models.Entities
{
    /// <summary>
    /// CategoryEntity represents a food category for organizing products in the store.
    /// 
    /// Categories help users browse and filter food items by type. Each food item belongs
    /// to a category, and categories are displayed prominently in the user interface with
    /// icons for visual identification and quick navigation.
    /// 
    /// Example: Pizza, Burgers, Desserts, Beverages, Salads, etc.
    /// </summary>
    public class CategoryEntity
    {
        /// <summary>
        /// Primary Key (PK)
        /// Unique identifier for each category in the database.
        /// Auto-generated by the database to uniquely identify each product category.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// The name of the category.
        /// Displayed to customers as a category label for browsing and filtering.
        /// A required field that must be provided when creating a category.
        /// Should be clear and easily understood by customers.
        /// 
        /// Example: "Pizza", "Burgers", "Desserts", "Beverages", "Salads"
        /// </summary>
        public required string Name { get; set; }

        /// <summary>
        /// URL/path to the category icon image.
        /// Displays a visual representation of the category in the UI.
        /// A required field that must be provided when creating a category.
        /// Should be a valid image URL pointing to an icon file (PNG, SVG, JPG, etc.).
        /// Icons help users quickly identify and navigate between categories.
        /// 
        /// Example: "https://cdn.example.com/icons/pizza-icon.svg" or "/images/categories/burger-icon.png"
        /// </summary>
        public required string IconURL { get; set; }
    }
}