namespace FoodEcommerceWebAPI.Models.Entities
{
    /// <summary>
    /// FoodItemsEntity represents a food product available in the ecommerce store.
    /// 
    /// This entity contains all the information about a food item including its name,
    /// description, price, category, stock quantity, and an image for display.
    /// Each food item can be added to shopping carts and orders by multiple customers.
    /// 
    /// Example: A "Margherita Pizza" priced at $15.99 with 50 units in stock.
    /// </summary>
    public class FoodItemsEntity
    {
        /// <summary>
        /// Primary Key (PK)
        /// Unique identifier for each food item in the database.
        /// Auto-generated by the database to uniquely identify each product.
        /// </summary>
        public int FoodItemId { get; set; }

        /// <summary>
        /// The name of the food item.
        /// Displayed to customers in the product catalog and search results.
        /// A required field that must be provided when creating a food item.
        /// Should be descriptive and user-friendly.
        /// 
        /// Example: "Margherita Pizza", "Grilled Chicken Burger", "Chocolate Cake"
        /// </summary>
        public required string Name { get; set; }

        /// <summary>
        /// A detailed description of the food item.
        /// Provides customers with information about ingredients, preparation, allergens, etc.
        /// A required field that must be provided when creating a food item.
        /// Should include relevant details to help customers make purchasing decisions.
        /// 
        /// Example: "Fresh mozzarella, basil, and tomato sauce on hand-tossed dough"
        /// </summary>
        public required string Description { get; set; }

        /// <summary>
        /// Foreign Key (FK) - References CategoryEntity
        /// Identifies which category this food item belongs to.
        /// Used to organize products (e.g., Pizza, Burgers, Desserts, Beverages).
        /// Allows customers to browse items by category.
        /// </summary>
        public int CategoryId { get; set; }

        /// <summary>
        /// The price of the food item.
        /// Stored as decimal(18,2) for precise financial calculations.
        /// Represents the cost to the customer for one unit of this item.
        /// This is the current price; historical prices are stored in OrderItemEntity.UnitPrice.
        /// 
        /// Example: 15.99 for a $15.99 pizza
        /// </summary>
        public decimal Price { get; set; }

        /// <summary>
        /// URL/path to the product image.
        /// Optional field - can be null if no image is available.
        /// Used to display product photos in the web interface and mobile app.
        /// Should link to a valid image file (PNG, JPG, etc.).
        /// 
        /// Example: "https://cdn.example.com/images/margherita-pizza.jpg" or "/images/products/pizza-001.jpg"
        /// </summary>
        public string? ImageUrl { get; set; }

        /// <summary>
        /// The quantity of this item currently in stock.
        /// Represents the number of units available for purchase.
        /// Should be updated when items are ordered or restocked.
        /// When StockQuantity reaches 0, the item should be marked as out of stock.
        /// 
        /// Example: 50 units means there are 50 Pizzas available for sale
        /// </summary>
        public int StockQuantity { get; set; }
    }
}