namespace FoodEcommerceWebAPI.Models.Entities
{
    /// <summary>
    /// OrderEntity represents a customer order/purchase in the food ecommerce system.
    /// 
    /// This entity captures all essential information about an order including the customer,
    /// order items, total amount, and current status. Each order can contain multiple items
    /// and is associated with a specific user.
    /// 
    /// Example: User places an order on 2026-01-20 for 2 Pizzas and 1 Burger totaling $35.99 with status "Pending".
    /// </summary>
    public class OrderEntity
    {
        /// <summary>
        /// Primary Key (PK)
        /// Unique identifier for each order in the database.
        /// Auto-generated by the database to uniquely identify each order.
        /// </summary>
        public int OrderId { get; set; }

        /// <summary>
        /// Foreign Key (FK) - References UserEntity
        /// Identifies which user/customer placed this order.
        /// Links this order to the user who made the purchase.
        /// </summary>
        public int UserId { get; set; }

        /// <summary>
        /// The date and time when the order was created/placed.
        /// Recorded automatically when the order is created in the system.
        /// Used for order history, filtering, and transaction records.
        /// 
        /// Example: 2026-01-20 14:30:45 represents when the customer checked out.
        /// </summary>
        public DateTime OrderDate { get; set; }

        /// <summary>
        /// The total monetary amount for the entire order.
        /// Calculated as the sum of all order items (quantity × unit price).
        /// Stored as decimal(18,2) for precise financial calculations.
        /// Includes the cost of all items in the order before taxes/shipping if applicable.
        /// 
        /// Example: 35.99 for an order containing 2 Pizzas ($15.99 each) and 1 Burger ($4.01).
        /// </summary>
        public decimal TotalAmount { get; set; }

        /// <summary>
        /// The current status/state of the order in its lifecycle.
        /// Tracks the progression of the order from creation to delivery.
        /// Default value is "Pending" when the order is first created.
        /// 
        /// Possible values:
        /// - "Pending": Order received but not yet processed
        /// - "Processing": Order being prepared/packed
        /// - "Shipped": Order has been sent out for delivery
        /// - "Delivered": Order has been received by customer
        /// - "Cancelled": Order was cancelled by user or system
        /// - "Failed": Order payment or processing failed
        /// 
        /// Example: Initially "Pending", then transitions to "Processing", then "Shipped", finally "Delivered".
        /// </summary>
        public string Status { get; set; } = "Pending";

        /// <summary>
        /// The shipping address where the order will be delivered.
        /// Optional property (nullable string) - can be null if not yet provided.
        /// Contains the full delivery address including street, city, state, and postal code.
        /// 
        /// Example: "123 Main Street, Apt 4B, New York, NY 10001"
        /// </summary>
        public string? ShippingAddress { get; set; }

        /// <summary>
        /// Navigation property to the User entity.
        /// Provides access to the customer who placed this order without needing manual joins.
        /// Uses the UserId foreign key to establish the relationship.
        /// Allows easy access to user details like name, email, and contact information.
        /// 
        /// Example: order.User will return the UserEntity object containing customer information.
        /// </summary>
        public virtual UserEntity User { get; set; } = null!;

        /// <summary>
        /// Navigation property to the collection of OrderItems.
        /// Contains all individual items/products that are part of this order.
        /// A one-to-many relationship where one order can have multiple items.
        /// Each OrderItemEntity contains details like quantity and unit price for that specific item.
        /// Initialized as an empty list to prevent null reference exceptions.
        /// 
        /// Example: order.OrderItems will return a list of 3 OrderItemEntity objects:
        /// - Pizza (Quantity: 2, UnitPrice: $15.99)
        /// - Burger (Quantity: 1, UnitPrice: $4.01)
        /// - Fries (Quantity: 1, UnitPrice: $2.99)
        /// </summary>
        public virtual ICollection<OrderItemEntity> OrderItems { get; set; } = new List<OrderItemEntity>();
    }
}
