namespace FoodEcommerceWebAPI.Models.Entities
{
    /// <summary>
    /// OrderItemEntity represents an individual product line item within a customer order.
    /// 
    /// This entity acts as a junction table between Order and FoodItems, storing details
    /// about each product included in an order along with the quantity and price at the time
    /// of purchase. This allows orders to maintain historical pricing even if product prices
    /// change in the future.
    /// 
    /// Example: If an order contains 2 Pizzas and 1 Burger, there would be two OrderItemEntity
    /// records - one for the Pizza line item and one for the Burger line item.
    /// </summary>
    public class OrderItemEntity
    {
        /// <summary>
        /// Primary Key (PK)
        /// Unique identifier for each order item record in the database.
        /// Auto-generated by the database to uniquely identify each line item in orders.
        /// </summary>
        public int OrderItemId { get; set; }

        /// <summary>
        /// Foreign Key (FK) - References OrderEntity
        /// Identifies which order this item belongs to.
        /// Links this order item to its parent order.
        /// Multiple order items can share the same OrderId (one order has many items).
        /// </summary>
        public int OrderId { get; set; }

        /// <summary>
        /// Foreign Key (FK) - References FoodItemsEntity
        /// Identifies which food product this order item represents.
        /// Links this order item to the product details (name, description, original price, etc.).
        /// Note: The original product may have changed since the order was placed.
        /// </summary>
        public int FoodItemId { get; set; }

        /// <summary>
        /// The quantity of the food item ordered.
        /// Represents how many units of this product the customer purchased in this order.
        /// Must be a positive integer (e.g., 1, 2, 5).
        /// 
        /// Example: Quantity of 2 means the customer ordered 2 Pizzas.
        /// </summary>
        public int Quantity { get; set; }

        /// <summary>
        /// The price per unit of the food item at the time the order was placed.
        /// This is a snapshot of the product price when the order was created, stored as decimal(18,2).
        /// 
        /// Important: This value remains fixed and does not change if the product price changes later.
        /// This ensures accurate historical records and prevents price discrepancies.
        /// 
        /// The line item total is calculated as: Quantity × UnitPrice
        /// Example: Quantity=2, UnitPrice=15.99 results in a line total of $31.98
        /// </summary>
        public decimal UnitPrice { get; set; }

        /// <summary>
        /// Navigation property to the parent Order entity.
        /// Provides access to the order that contains this item without needing manual joins.
        /// Uses the OrderId foreign key to establish the relationship.
        /// Allows easy access to order information like order date, total amount, and shipping address.
        /// 
        /// Example: orderItem.Order will return the OrderEntity object containing this item.
        /// </summary>
        public virtual OrderEntity Order { get; set; } = null!;

        /// <summary>
        /// Navigation property to the FoodItemsEntity (Product).
        /// Provides access to the product details (name, description, current price, stock, etc.) without needing manual joins.
        /// Uses the FoodItemId foreign key to establish the relationship.
        /// 
        /// Important: While FoodItem.Price may have changed since this order was placed,
        /// the UnitPrice property of this OrderItemEntity contains the price at the time of purchase.
        /// 
        /// Example: orderItem.FoodItem will return the FoodItemsEntity object with current product information.
        /// </summary>
        public virtual FoodItemsEntity FoodItem { get; set; } = null!;
    }
}
