namespace FoodEcommerceWebAPI.Models.Entities
{
    /// <summary>
    /// ReviewEntity represents a product review/rating from a customer.
    /// 
    /// This entity stores customer feedback for food items including:
    /// - Rating (1-5 stars)
    /// - Written review/comment
    /// - Review date
    /// - Customer who wrote the review
    /// 
    /// Reviews help other customers make informed purchasing decisions
    /// and provide valuable feedback to the business.
    /// </summary>
    public class ReviewEntity
    {
        /// <summary>
        /// Primary Key (PK)
        /// Unique identifier for each review.
        /// Auto-generated by the database.
        /// </summary>
        public int ReviewId { get; set; }

        /// <summary>
        /// Foreign Key (FK) - References FoodItemsEntity
        /// Identifies which product this review is for.
        /// </summary>
        public int FoodItemId { get; set; }

        /// <summary>
        /// Foreign Key (FK) - References UserEntity
        /// Identifies the customer who wrote this review.
        /// </summary>
        public int UserId { get; set; }

        /// <summary>
        /// The rating given by the customer (1-5 stars).
        /// 
        /// Valid values:
        /// - 1: Poor
        /// - 2: Fair
        /// - 3: Good
        /// - 4: Very Good
        /// - 5: Excellent
        /// </summary>
        public int Rating { get; set; }

        /// <summary>
        /// The written review/comment from the customer.
        /// Optional: Customer may leave only a rating without comment.
        /// Maximum 1000 characters.
        /// </summary>
        public string? Comment { get; set; }

        /// <summary>
        /// The date and time when the review was posted.
        /// </summary>
        public DateTime CreatedDate { get; set; }

        /// <summary>
        /// The date and time when the review was last updated.
        /// Null if never updated.
        /// </summary>
        public DateTime? UpdatedDate { get; set; }

        /// <summary>
        /// Navigation property to the FoodItemsEntity.
        /// Provides access to the product being reviewed.
        /// </summary>
        public virtual FoodItemsEntity FoodItem { get; set; } = null!;

        /// <summary>
        /// Navigation property to the UserEntity.
        /// Provides access to the customer who wrote the review.
        /// </summary>
        public virtual UserEntity User { get; set; } = null!;
    }
}
