namespace FoodEcommerceWebAPI.Models.Entities
{
    /// <summary>
    /// RoleEntity represents a user role for access control and authorization.
    /// 
    /// Roles define what permissions and functionalities are available to different types of users.
    /// Each user can be assigned one or more roles (e.g., Customer, Admin, Manager).
    /// This entity supports role-based access control (RBAC) for managing system permissions.
    /// 
    /// Example: A user with the "Admin" role can manage products and view all orders,
    /// while a user with the "Customer" role can only view their own orders.
    /// </summary>
    public class RoleEntity
    {
        /// <summary>
        /// Primary Key (PK)
        /// Unique identifier for each role record in the database.
        /// Auto-generated by the database.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Foreign Key (FK) - References UserEntity
        /// Identifies which user this role is assigned to.
        /// Links this role assignment to a specific user account.
        /// A required field that must be provided when creating a role record.
        /// A user can have multiple RoleEntity records for different roles.
        /// </summary>
        public required int UserID { get; set; }

        /// <summary>
        /// The name of the role assigned to the user.
        /// Optional field - can be null if role is not yet specified.
        /// Defines what type of user this is and what actions they can perform.
        /// 
        /// Common role values:
        /// - "Admin": Full system access including product and order management
        /// - "Manager": Limited administrative access, can manage products
        /// - "Customer": Standard user access, can browse, order, and view personal information
        /// - "Guest": Limited access, can browse products without account
        /// 
        /// Example: "Admin", "Manager", "Customer"
        /// </summary>
        public string? RoleName { get; set; }
    }
}