namespace FoodEcommerceWebAPI.Models.Entities
{
    /// <summary>
    /// UserEntity represents a registered customer/user in the food ecommerce system.
    /// 
    /// This entity stores user authentication credentials and personal information.
    /// Each user can have multiple addresses (for delivery and billing) and multiple orders
    /// representing their purchase history. This entity is central to the system as it
    /// connects to carts, orders, and addresses.
    /// 
    /// Soft Delete: The IsActive flag allows for logical deletion instead of physical deletion.
    /// When a user requests account deletion, IsActive is set to false rather than deleting the record.
    /// This preserves data for auditing, historical records, and potential account recovery.
    /// 
    /// Example: A customer named "John Doe" with email "john@example.com" has orders and multiple addresses.
    /// </summary>
    public class UserEntity
    {
        /// <summary>
        /// Primary Key (PK)
        /// Unique identifier for each user in the database.
        /// Auto-generated by the database to uniquely identify each customer.
        /// </summary>
        public int UserId { get; set; }

        /// <summary>
        /// The user's display/login name.
        /// Unique identifier used by the user to log in or be identified in the system.
        /// A required field that must be provided when creating a user account.
        /// 
        /// Example: "johndoe", "jane_smith", "pizza_lover_123"
        /// </summary>
        public required string UserName { get; set; }

        /// <summary>
        /// The user's phone number.
        /// Used for order notifications and customer support contact.
        /// A required field that must be provided when registering.
        /// Should be stored in a consistent format for international compatibility.
        /// 
        /// Example: "+1-555-123-4567" or "555-123-4567"
        /// </summary>
        public required string PhoneNumber { get; set; }

        /// <summary>
        /// The user's email address.
        /// Used for account login, order confirmation, and communication.
        /// A required field that must be provided when registering.
        /// Should be unique to prevent multiple accounts with the same email.
        /// 
        /// Example: "john.doe@example.com"
        /// </summary>
        public required string Email { get; set; }

        /// <summary>
        /// The hashed password for authentication.
        /// Stores the cryptographically hashed version of the user's password (never store plain text).
        /// A required field that must be provided when registering.
        /// Should be hashed using a secure algorithm like BCrypt, not stored as plain text.
        /// 
        /// Note: This should be hashed using BCrypt or similar before storage.
        /// Example: "$2b$12$R9h/cIPz0gi.URNNX3kh2OPST9/PgBkqquzi.Ss7KIUgO2t0jWMUW"
        /// </summary>
        public required string PasswordHash { get; set; }

        /// <summary>
        /// Soft delete flag indicating whether the user account is active.
        /// 
        /// Values:
        /// - true (1): User account is active and can log in, place orders, and perform operations
        /// - false (0): User account is logically deleted but preserved in database for:
        ///   - Historical audit trail
        ///   - Order records and transaction history
        ///   - Legal/compliance requirements
        ///   - Potential account recovery
        /// 
        /// Default: true (set to true when user registers)
        /// 
        /// Soft Delete Benefits:
        /// - Preserves data integrity and referential relationships
        /// - Maintains audit trail and historical records
        /// - Allows account reactivation if needed
        /// - Complies with data retention policies
        /// - Prevents orphaned orders and address records
        /// 
        /// When IsActive = false:
        /// - User cannot log in
        /// - User data is excluded from all queries (filtered in DbContext)
        /// - Orders and addresses remain linked for historical purposes
        /// - User record is preserved in database
        /// 
        /// Example: User deletes account → IsActive becomes false → User data hidden but preserved
        /// </summary>
        public bool IsActive { get; set; } = true;

        /// <summary>
        /// Navigation property to the collection of Addresses.
        /// Represents all addresses (shipping, billing, alternate) associated with this user.
        /// A one-to-many relationship where one user can have multiple addresses.
        /// Initialized as an empty list to prevent null reference exceptions.
        /// 
        /// Example: user.Addresses returns a list of all the user's saved addresses.
        /// </summary>
        public virtual ICollection<AddressEntitiy> Addresses { get; set; } = new List<AddressEntitiy>();

        /// <summary>
        /// Navigation property to the collection of Orders.
        /// Represents all orders/purchases made by this user.
        /// A one-to-many relationship where one user can have multiple orders.
        /// Initialized as an empty list to prevent null reference exceptions.
        /// Provides easy access to the user's complete purchase history.
        /// 
        /// Example: user.Orders returns a list of all orders placed by this user.
        /// </summary>
        public virtual ICollection<OrderEntity> Orders { get; set; } = new List<OrderEntity>();

        /// <summary>
        /// Navigation property to the Wishlist.
        /// Represents the user's wishlist containing favorite items.
        /// Each user has exactly one wishlist.
        /// </summary>
        public virtual WishlistEntity? Wishlist { get; set; }
    }
}