namespace FoodEcommerceWebAPI.Models.Entities
{
    /// <summary>
    /// WishlistItemEntity represents an individual food item in a user's wishlist.
    /// 
    /// This entity is a junction table between Wishlist and FoodItems,
    /// allowing multiple products to be added to a wishlist.
    /// </summary>
    public class WishlistItemEntity
    {
        /// <summary>
        /// Primary Key (PK)
        /// Unique identifier for each wishlist item.
        /// Auto-generated by the database.
        /// </summary>
        public int WishlistItemId { get; set; }

        /// <summary>
        /// Foreign Key (FK) - References WishlistEntity
        /// Identifies which wishlist this item belongs to.
        /// </summary>
        public int WishlistId { get; set; }

        /// <summary>
        /// Foreign Key (FK) - References FoodItemsEntity
        /// Identifies which food product is in the wishlist.
        /// </summary>
        public int FoodItemId { get; set; }

        /// <summary>
        /// The date when this item was added to the wishlist.
        /// </summary>
        public DateTime AddedDate { get; set; }

        /// <summary>
        /// Navigation property to the WishlistEntity.
        /// Provides access to the parent wishlist.
        /// </summary>
        public virtual WishlistEntity Wishlist { get; set; } = null!;

        /// <summary>
        /// Navigation property to the FoodItemsEntity.
        /// Provides access to the product details.
        /// </summary>
        public virtual FoodItemsEntity FoodItem { get; set; } = null!;
    }
}
