namespace FoodEcommerceWebAPI.Models.Entities
{
    /// <summary>
    /// WishlistEntity represents a user's wishlist of favorite products.
    /// 
    /// This entity allows customers to save products they want to purchase later
    /// or want to keep track of their favorite items.
    /// 
    /// Each user has one wishlist that can contain multiple food items.
    /// </summary>
    public class WishlistEntity
    {
        /// <summary>
        /// Primary Key (PK)
        /// Unique identifier for each wishlist.
        /// Auto-generated by the database.
        /// </summary>
        public int WishlistId { get; set; }

        /// <summary>
        /// Foreign Key (FK) - References UserEntity
        /// Identifies which user this wishlist belongs to.
        /// One user can have only one wishlist.
        /// </summary>
        public int UserId { get; set; }

        /// <summary>
        /// The date when the wishlist was created.
        /// </summary>
        public DateTime CreatedDate { get; set; }

        /// <summary>
        /// The date when the wishlist was last updated.
        /// Updated whenever items are added or removed.
        /// </summary>
        public DateTime LastUpdatedDate { get; set; }

        /// <summary>
        /// Navigation property to the UserEntity.
        /// Provides access to the user who owns this wishlist.
        /// </summary>
        public virtual UserEntity User { get; set; } = null!;

        /// <summary>
        /// Navigation property to the collection of WishlistItems.
        /// Represents all products in this wishlist.
        /// </summary>
        public virtual ICollection<WishlistItemEntity> WishlistItems { get; set; } = new List<WishlistItemEntity>();
    }
}
